### ISSUE TITLE
TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by lacruzanthony** [getDanArias/Mithril-Sample-App#1]
Hello. I'm trying to run de command:

`npm run install`

and got this error:

> TypeError:  Cannot read property 'properties' of undefined at module.exports (C:\Users\HP\Documents\Proyectos personales\Frameworksjavascript\Mithrill.js\Demos\Demo 2\conference-tracker\node_modules\webpack-cli\bin\config-yargs.js:89:48) 
at C:\Users\HP\Documents\Proyectos personales\Frameworks javascript\Mithrill.js\Demos\Demo2\conference-tracker\node_modules\webpack-cli\bin\webpack.js:60:27 at Object.<anonymous> (C:\Users\HP\Documents\Proyectos personales\Frameworks javascript\Mithrill.js\Demos\Demo 2\conference-tracker\node_modules\webpack-cli\bin\webpack.js:515:3)
>    at Module._compile (module.js:653:30)
>    at Object.Module._extensions..js (module.js:664:10)
  >  at Module.load (module.js:566:32)
>    at tryModuleLoad (module.js:506:12)
>    at Function.Module._load (module.js:498:3)
>    at Module.require (module.js:597:17)
>   at require (internal/module.js:11:18)
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! conference-tracker@1.0.0 build: `webpack --config webpack.config.js`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the conference-tracker@1.0.0 build script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2018-11-03T20_21_49_259Z-debug.log

The log file is attached. 

Thanks

[2018-11-03T20_21_49_259Z-debug.log](https://github.com/getDanArias/Mithril-Sample-App/files/2545373/2018-11-03T20_21_49_259Z-debug.log)

**Comment by DanOnCall** [comment]
@lacruzanthony Thanks for bringing this up! I was able to find the problem:

https://github.com/webpack/webpack/issues/8082

Updating `webpack-cli` as follows fixes the issue:

`"webpack-cli": "^3.1.1",`

👍

**Comment by lacruzanthony** [comment]
@dan-auth0 oh great! It is working.

Thanks! 😄
